#!/bin/bash
# Prevent Claude from editing auto-generated files.
# Exit 2 = block the tool call.

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.file // empty')

case "$FILE_PATH" in
  */vendor/javascript/*)
    echo "BLOCKED: $FILE_PATH is auto-generated by importmap. Do not edit." >&2
    exit 2
    ;;
  */app/frontend/serializers/*)
    echo "BLOCKED: $FILE_PATH is auto-generated by typelizer. Do not edit." >&2
    exit 2
    ;;
  */db/*schema*.rb)
    echo "BLOCKED: $FILE_PATH is auto-generated by Rails migrations. Do not edit." >&2
    exit 2
    ;;
esac

exit 0
