// Typelizer digest 35e85a86127d6efc1f4ff9955655a470
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface CFP {
  id: string;
  tracks: Record<string, string>;
  field_names: Record<string, string> | undefined;
  is_closed: boolean;
}

export default CFP;
