// Typelizer digest 09b9a241cd6a6ab84c4bb9627df62a71
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Proposal} from "@/serializers"

type CFP = {
  id: string;
  tracks: Record<Exclude<Proposal["track"], null>,string>;
  field_names: Record<string,string> | undefined;
  is_closed: boolean;
}

export default CFP;
