// Typelizer digest 3e9f23a812264519341fff97b2a55919
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Proposal} from "@/serializers"

type CFP = {
  id: string;
  primary: boolean;
  tracks: Record<Exclude<Proposal["track"], null>,string>;
  field_names: Record<string,string> | undefined;
  is_closed: boolean;
}

export default CFP;
