// Typelizer digest 6ce18cde853a7d3eeaef13a7f50a6e73
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type ProposalStatus = "draft" | "submitted" | "accepted" | "rejected" | "waitlisted" | "confirmed" | "declined";
export type ProposalTrack = "startup" | "scale" | "general";
export type ReviewStatus = "pending" | "submitted";
