// Typelizer digest 5e3498b5cac4c526064dca0871d0bdd6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {SpeakerProfile, ProposalTrack, ProposalStatus} from "@/serializers"

type EvaluationsProposal = {
  id: string;
  title: string | null;
  details: string | null;
  abstract: string | null;
  pitch: string | null;
  track: ProposalTrack | null;
  status: ProposalStatus;
  submitted_at: string | null;
  score: number;
  reviews_count: number;
  speaker_profile: SpeakerProfile | null;
}

export default EvaluationsProposal;
