// Typelizer digest 294d8b1c8473317c85d3ee9c2767413d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {SpeakerProfile} from "@/serializers"

type EvaluationsProposal = {
  id: string;
  title: string | null;
  details: string | null;
  abstract: string | null;
  pitch: string | null;
  track: "general" | null;
  status: "draft" | "submitted" | "accepted" | "rejected" | "waitlisted" | "confirmed" | "declined";
  submitted_at: string | null;
  score: number;
  reviews_count: number;
  speaker_profile: SpeakerProfile | null;
}

export default EvaluationsProposal;
