// Typelizer digest 010f6661c4c2c36372d90c5bb8ca387b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Proposal, CFP, SpeakerProfile} from '../serializers'

type PagesProposalsNew = {
  proposal: Proposal;
  cfp: CFP;
  speaker: SpeakerProfile;
}

export default PagesProposalsNew;
