// Typelizer digest 18fe8019f4bcce02980fcf18eba7d50b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PagesHomeIndex = {
  oauth_providers: string[];
}

export default PagesHomeIndex;
