// Typelizer digest 322b32893bd041b4b0d7fa90bda7da43
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Proposal} from '../serializers'

type PagesProposalsIndex = {
  proposals: Array<Proposal>;
}

export default PagesProposalsIndex;
