// Typelizer digest fe660d466800100862bc237733a15489
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Proposal = {
  id: number;
  title: string | null;
  details: string | null;
  abstract: string | null;
  pitch: string | null;
  track: "oss" | "scale" | "general" | "startup" | "workshop" | null;
  status: "draft" | "submitted" | "accepted" | "rejected" | "waitlisted";
  submitted_at: string | null;
}

export default Proposal;
