// Typelizer digest b5ace05a7caeb601928bf69d52266166
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Proposal = {
  id: string;
  cfp_id: string | null;
  title: string | null;
  details: string | null;
  abstract: string | null;
  pitch: string | null;
  track: "oss" | "scale" | "general" | "startup" | "workshop" | null;
  status: "draft" | "submitted" | "accepted" | "rejected" | "waitlisted" | "confirmed" | "declined";
  submitted_at: string | null;
  can_edit: boolean;
}

export default Proposal;
