// Typelizer digest 89f7af77bf9fca360948927cd2503280
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Proposal = {
  id: number;
  title: string | null;
  details: string | null;
  abstract: string | null;
  pitch: string | null;
  track: "oss" | "scale" | "general" | null;
  status: "draft" | "submitted" | "accepted" | "rejected" | "waitlisted";
  submitted_at: string | null;
}

export default Proposal;
