// Typelizer digest 63871c7e3c2453755a4726dd4a0b30de
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Proposal, User, Evaluation} from '../serializers'

type Review = {
  id: number;
  comment: string | null;
  status: "pending" | "submitted";
  scores: Record<string,number>;
  proposal: Proposal | null;
  user: User | null;
  evaluation: Evaluation | null;
}

export default Review;
