// Typelizer digest 95e4786f51da77a638a48cdcbb3b1261
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {SpeakerProfile, Proposal, User, Evaluation} from "@/serializers"

type Review = {
  id: number;
  comment: string | null;
  status: "pending" | "submitted";
  scores: Record<string,number>;
  score: number | null;
  proposal: Proposal | null;
  user: User | null;
  evaluation: Evaluation | null;
  speaker: SpeakerProfile;
}

export default Review;
