// Typelizer digest f49140d759bb3195ec43f19577867e2f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Proposal, User, Evaluation} from '../serializers'

type Review = {
  id: number;
  comment: string | null;
  status: "pending" | "submitted";
  scores: Record<string,number>;
  score: number | null;
  proposal: Proposal | null;
  user: User | null;
  evaluation: Evaluation | null;
}

export default Review;
