// Typelizer digest 105b6ef31fb4dac7dcb33a45537bf8e0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {User} from '../serializers'

type Shared = {
  user?: User;
  flash: Record<"alert" | "notice", string>;
  cfp_closed: boolean;
}

export default Shared;
