// Typelizer digest 0059ff71e78b274a7a7caff0aac3a527
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SpeakerProfile = {
  name: string;
  email: string;
  bio: string | null;
  company: string | null;
  role: string | null;
  socials: string | null;
  photo_url: string | null;
}

export default SpeakerProfile;
