// Typelizer digest dabddaf0fbb0abafdfa36734f9bb44d0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SpeakerProfile = {
  name: string;
  email: string;
  bio: string | null;
  company: string | null;
  socials: string | null;
  photo_url: string | null;
}

export default SpeakerProfile;
