// Typelizer digest 2401d18312d1841295e4548936788162
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SpeakerProfile = {
  name: string;
  email: string;
  bio: string | null;
  company: string | null;
  role: string | null;
  socials: string | null;
  photo_url: string | null;
}

export default SpeakerProfile;
