// Typelizer digest 01fb352366ec9ae312c4d24032f9c3c3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  name: string;
  email: string;
}

export default User;
