// Typelizer digest 13c07b6a471cd9c3accf7eee1c012a98
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface User {
  id: number;
  name: string;
  email: string;
  is_reviewer: boolean;
}

export default User;
