// Typelizer digest ff56aa91bbee0ed7929cd32b9fc319e1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  name: string;
  email: string;
  is_reviewer: boolean;
}

export default User;
