default: &default
  host: "localhost"
  port: 3000
  cfp_deadline: "2025-07-14T00:00:00-07:00"
  startup_deadline: "2025-10-14T00:00:00-07:00"

development:
  <<: *default

test:
  <<: *default
  cfp_deadline: ~
  startup_deadline: ~

production: &production
  <<: *default
  host: "cfp.sfruby.com"
  port: 443
  
